export const categoryData = [
  {
    heading: 'Frozen Ready to Eat',
    subheading: 'Authentic taste, ready for your kitchen.',
    items: [
      {
        id: 'kerala_porotta',
        title: 'Kerala Porotta',
        image: '/products/kerala-porotta-p.png',
        href: '#',
      },
      {
        id: 'malabar_porotta',
        title: 'Malabar Porotta',
        image: '/products/malabar-porotta-p.png',
        href: '#',
      },
      {
        id: 'kothu_porotta',
        title: 'Kothu Porotta',
        image: '/products/kothu-porotta-p.png',
        href: '#',
      },
      {
        id: 'idli_catering_pack',
        title: 'Idli Catering Pack',
        image: '/products/idli-catering-pack-p.png',
        href: '#',
      },
      {
        id: 'parippu_vada',
        title: 'Parippu Vada',
        image: '/products/parippu-vada-p.png',
        href: '#',
      },
      {
        id: 'idiyappam',
        title: 'Idiyappam',
        image: '/products/idiyappam-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Frozen Vegetables',
    subheading: 'Farm fresh vegetables, frozen to perfection.',
    items: [
      {
        id: 'grated_coconut',
        title: 'Grated Coconut',
        image: '/products/grated-coconut-p.png',
        href: '#',
      },
      {
        id: 'sliced_coconut',
        title: 'Sliced Coconut',
        image: '/products/sliced-coconut-p.png',
        href: '#',
      },
      {
        id: 'drumstick',
        title: 'Drumstick',
        image: '/products/drumstick-p.png',
        href: '#',
      },
      {
        id: 'baby_jackfruit',
        title: 'Baby Jackfruit',
        image: '/products/baby-jackfruit-p.png',
        href: '#',
      },
      {
        id: 'sambar_mix',
        title: 'Sambar Mix',
        image: '/products/sambar-mix-p.png',
        href: '#',
      },
      {
        id: 'shallots',
        title: 'Shallots',
        image: '/products/shallots-p.png',
        href: '#',
      },
      {
        id: 'tapioca',
        title: 'Tapioca',
        image: '/products/tapioca-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Dry Products ...',
    subheading: 'Traditional mixes and ready-to-cook essentials.',
    items: [
      {
        id: 'Appam_Podi',
        title: 'Appam Podi',
        image: '/products/appam-p.png',
        description:
          'Made from premium rice, our Appam Podi helps you prepare traditional Kerala appams effortlessly, preserving the authentic taste and texture of homemade goodness.',
        href: '/products',
        featured: true,
      },
      {
        id: 'Steam_Puttu_Podi',
        title: 'Steam Puttu Podi',
        image: '/products/puttu-p.png',
        href: '#',
      },
      {
        id: 'Matta_Aval',
        title: 'Matta Aval',
        image: '/products/aval-p.png',
        href: '#',
      },
      {
        id: 'rawa',
        title: 'Roasted Rawa',
        image: '/products/rawa-p.png',
        href: '#',
      },
      {
        id: 'Avalose_Podi',
        title: 'Avalose Podi',
        image: '/products/avalose-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Spices...',
    subheading: 'Authentic Indian spices and flavorful condiments.',
    items: [
      {
        id: 'black_pepper',
        title: 'Black Pepper',
        image: '/products/black-pepper-p.png',
        description: 'Freshly ground black pepper, perfect for adding authentic flavor to your dishes.',
        href: '/products/black-pepper',
        featured: true,
      },
      {
        id: 'cardamom',
        title: 'Cardamom',
        image: '/products/cardamom-p.png',
        href: '#',
      },
      {
        id: 'cumin',
        title: 'Cumin',
        image: '/products/cumin-p.png',
        href: '#',
      },
      {
        id: 'turmeric',
        title: 'Turmeric',
        image: '/products/turmeric-p.png',
        href: '#',
      },
      {
        id: 'dry_ginger',
        title: 'Dry Ginger',
        image: '/products/dry-ginger-p.png',
        href: '#',
      },
      {
        id: 'chilli',
        title: 'Chilli',
        image: '/products/chilli-p.png',
        href: '#',
      },
      {
        id: 'coriander',
        title: 'Coriander',
        image: '/products/coriander-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Rice...',
    subheading: 'Premium quality rice and nutritious grains.',
    items: [
      {
        id: 'basmati_rice',
        title: 'Basmati Rice',
        image: '/products/basmati-p.png',
        description:
          'Long-grain aromatic basmati rice, aged to perfection. Known for its distinctive fragrance and fluffy texture, ideal for biryanis, pulaos, and everyday meals.',
        href: '/products/basmati',
        featured: true,
      },
      {
        id: 'matta_rice',
        title: 'Matta Rice',
        image: '/products/matta-rice-p.png',
        href: '#',
      },
      {
        id: 'mandhi_rice',
        title: 'Mandhi Rice',
        image: '/products/mandhi-rice-p.png',
        href: '#',
      },
      {
        id: 'jeeraka_rice',
        title: 'Jeeraka Rice',
        image: '/products/jeeraka-rice-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Snacks...',
    subheading: 'Traditional and delicious Kerala snacks.',
    items: [
      {
        id: 'banana_chips',
        title: 'Banana Chips',
        image: '/products/banana-chips-p.png',
        description:
          'Freshly roasted banana chips, perfect for snacking and adding a crunchy texture to your meals.',
        href: '/products/banana-chips',
        featured: true,
      },
      {
        id: 'spiced_mixture',
        title: 'Spiced Mixture',
        image: '/products/spiced-mixture-p.png',
        href: '#',
      },
      {
        id: 'pakkavada',
        title: 'Pakkavada',
        image: '/products/pakkavada-p.png',
        href: '#',
      },
      {
        id: 'tapioca_chips',
        title: 'Tapioca Chips',
        image: '/products/tapioca-chips-p.png',
        href: '#',
      },
      {
        id: 'jackfruit_chips',
        title: 'Jackfruit Chips',
        image: '/products/jackfruit-chips-p.png',
        href: '#',
      },
      {
        id: 'murukku',
        title: 'Murukku',
        image: '/products/murukku-p.png',
        href: '#',
      },
      {
        id: 'sharkara_varatti',
        title: 'Sharkara Varatti',
        image: '/products/sharkara-varatti-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Masala...',
    subheading: 'Authentic Indian masala and flavorful condiments.',
    items: [
      {
        id: 'jeerakam_powder',
        title: 'Jeerakam Powder',
        image: '/products/jeerakam-p.png',
        description:
          'Finely ground jeerakam (cumin) powder, known for its warm, earthy aroma and essential in many Indian dishes.',
        href: '/products/jeerakam-powder',
        featured: true,
      },
      {
        id: 'sambar_powder',
        title: 'Sambar Powder',
        image: '/products/sambar-p.png',
        href: '#',
      },
      {
        id: 'paprika_powder',
        title: 'Paprika Powder',
        image: '/products/paprika-p.png',
        href: '#',
      },
      {
        id: 'whole_turmeric',
        title: 'Whole Turmeric',
        image: '/products/whole-turmeric-p.png',
        href: '#',
      },
      {
        id: 'rasam_powder',
        title: 'Rasam Powder',
        image: '/products/rasam-p.png',
        href: '#',
      },
      {
        id: 'black_pepper_powder',
        title: 'Black Pepper Powder',
        image: '/products/black-pepper-p.png',
        href: '#',
      },
      {
        id: 'red_chilli_powder',
        title: 'Red Chilli Powder',
        image: '/products/red-chilli-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Pickles...',
    subheading: 'Tangy, spicy, and authentic Kerala pickles to tantalize your taste buds.',
    items: [
      {
        id: 'garlic_pickles',
        title: 'Garlic Pickles',
        image: '/products/garlic-pickles-p.png',
        description: 'A spicy and tangy pickle made from fresh garlic cloves, perfect with any meal.',
        href: '/products/garlic-pickles',
        featured: true,
      },
      {
        id: 'cut_mango_pickles',
        title: 'Cut Mango Pickles',
        image: '/products/cut-mango-pickles-p.png',
        href: '#',
      },
      {
        id: 'lime_pickles',
        title: 'Lime Pickles',
        image: '/products/lime-pickles-p.png',
        href: '#',
      },
      {
        id: 'ginger_pickles',
        title: 'Ginger Pickles',
        image: '/products/ginger-pickles-p.png',
        href: '#',
      },
      {
        id: 'dates_pickles',
        title: 'Dates Pickles',
        image: '/products/dates-pickles-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
  {
    heading: 'Zere Specials...',
    subheading: 'Discover our exclusive range of specialty powders, snacks, and unique culinary delights.',
    items: [
      {
        id: 'appam_podi',
        title: 'Appam Podi',
        image: '/products/appam-podi-p.png',
        description: 'A spicy and tangy pickle made from fresh garlic cloves, perfect with any meal.',
        href: '/products/appam-podi',
        featured: true,
      },
      {
        id: 'steamed_puttu_podi',
        title: 'Steamed Puttu Podi',
        image: '/products/steamed-puttu-podi-p.png',
        href: '#',
      },
      {
        id: 'roasted_rava',
        title: 'Roasted Rava',
        image: '/products/roasted-rava-p.png',
        href: '#',
      },
      {
        id: 'matta_aval',
        title: 'Matta Aval',
        image: '/products/matta-aval-p.png',
        href: '#',
      },
      {
        id: 'roasted_matta_aval',
        title: 'Roasted Matta Aval',
        image: '/products/roasted-matta-aval-p.png',
        href: '#',
      },
      {
        id: 'avlose_podi',
        title: 'Avlose Podi',
        image: '/products/avlose-podi-p.png',
        href: '#',
      },
      {
        id: 'kanthari_mango_chutney',
        title: 'Kanthari Mango Chutney',
        image: '/products/kanthari-mango-chutney-p.png',
        href: '#',
      },
      {
        id: 'kanthari_gooseberry_chutney',
        title: 'Kanthari Gooseberry Chutney',
        image: '/products/kanthari-gooseberry-chutney-p.png',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '#',
  },
];
