export const categoryData = [
  {
    heading: 'Frozen Ready to Eat',
    subheading: 'Authentic taste, ready for your kitchen.',
    items: [
      {
        id: 'kerala_porotta',
        title: 'Kerala Porotta',
        image: '/products/porotta/porotta-p3.jpg',
        description: 'Flaky, layered flatbread that pairs perfectly with curries.',
        href: '#',
      },
      {
        id: 'malabar_porotta',
        title: 'Malabar Porotta',
        image: '/products/porotta/porotta-p2.jpg',
        description: 'Traditional Malabar style layered paratha, soft and delicious.',
        href: '#',
      },
      {
        id: 'kothu_porotta',
        title: 'Kothu Porotta',
        image: '/products/porotta/porotta-p1.jpg',
        description: 'Shredded porotta stir-fried with spices, a popular street food delicacy.',
        href: '#',
      },
      {
        id: 'idli_catering_pack',
        title: 'Idli Catering Pack',
        image: '/products/idli/idli-p.jpeg',
        description: 'Soft and fluffy steamed rice cakes, ideal for bulk serving.',
        href: '#',
      },
      {
        id: 'parippu_vada',
        title: 'Parippu Vada',
        image: '/products/snacks/parippuvada.jpg',
        description: 'Crunchy lentil fritters, a classic tea-time snack.',
        href: '#',
      },
      {
        id: 'idiyappam',
        title: 'Idiyappam',
        image: '/products/snacks/idiyappam.png',
        description: 'Steamed rice noodles, light and perfect for breakfast or dinner.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/frozen-ready-to-eat',
  },
  {
    heading: 'Frozen Vegetables',
    subheading: 'Farm fresh vegetables, frozen to perfection.',
    items: [
      {
        id: 'sliced_coconut',
        title: 'Sliced Coconut',
        image: '/products/coconut/coconut-p1.jpeg',
        description: 'Fresh coconut slices, frozen to retain natural sweetness and texture.',
        href: '#',
      },
      {
        id: 'grated_coconut',
        title: 'Grated Coconut',
        image: '/products/coconut/coconut-p2.jpeg',
        description: 'Convenient grated coconut, ready to use for curries and desserts.',
        href: '#',
      },
      {
        id: 'drumstick',
        title: 'Drumstick',
        image: '/products/vegetables/drumstick.jpeg',
        description: 'Tender drumsticks, essential for authentic sambar and avial.',
        href: '#',
      },
      {
        id: 'baby_jackfruit',
        title: 'Baby Jackfruit',
        image: '/products/vegetables/jackfruit-p.png',
        description: 'Young jackfruit chunks, perfect for curries and stir-fries.',
        href: '#',
      },
      {
        id: 'sambar_mix',
        title: 'Sambar Mix',
        image: '/products/vegetables/sambar.png',
        description: 'A mix of essential vegetables for preparing traditional Sambar quickly.',
        href: '#',
      },
      {
        id: 'shallots',
        title: 'Shallots',
        image: '/products/vegetables/shallots.png',
        description: 'Peeled shallots (small onions), adding distinct flavor to your dishes.',
        href: '#',
      },
      {
        id: 'tapioca',
        title: 'Tapioca',
        image: '/products/vegetables/tapioca.png',
        description: 'Cleaned and cut tapioca, ready to boil or steam.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/frozen-vegetables',
  },
  {
    heading: 'Dry Products ...',
    subheading: 'Traditional mixes and ready-to-cook essentials.',
    items: [
      {
        id: 'Appam_Podi',
        title: 'Appam Podi',
        image: '/products/powders/appam-p.png',
        description:
          'Made from premium rice, our Appam Podi helps you prepare traditional Kerala appams effortlessly, preserving the authentic taste and texture of homemade goodness.',
        href: '/products',
        featured: true,
      },
      {
        id: 'Steam_Puttu_Podi',
        title: 'Steam Puttu Podi',
        image: '/products/powders/puttu-p.png',
        description: 'Coarse rice flour blend for making soft and fluffy steamed puttu.',
        href: '#',
      },
      {
        id: 'Matta_Aval',
        title: 'Matta Aval',
        image: '/products/powders/aval-p.png',
        description: 'Flattened rice made from Matta rice, rich in nutrients and taste.',
        href: '#',
      },
      {
        id: 'rawa',
        title: 'Roasted Rawa',
        image: '/products/powders/rawa-p.png',
        description: 'Pre-roasted semolina, ideal for upma, kesari, and other dishes.',
        href: '#',
      },
      {
        id: 'Avalose_Podi',
        title: 'Avalose Podi',
        image: '/products/powders/avalose-p.png',
        description: 'Traditional roasted rice powder snack, best enjoyed with sugar or banana.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/dry-products',
  },
  {
    heading: 'Spices...',
    subheading: 'Authentic Indian spices and flavorful condiments.',
    items: [
      {
        id: 'black_pepper',
        title: 'Black Pepper',
        image: '/products/spices/pepper.png',
        description: 'Freshly ground black pepper, perfect for adding authentic flavor to your dishes.',
        href: '#',
        featured: true,
      },
      {
        id: 'cardamom',
        title: 'Cardamom',
        image: '/products/spices/cardamom.png',
        description: 'Aromatic green cardamom pods, essential for sweets and savory dishes.',
        href: '#',
      },
      {
        id: 'cumin',
        title: 'Cumin',
        image: '/products/spices/cumin.png',
        description: 'Earthy cumin seeds, a staple spice for tempering and flavoring.',
        href: '#',
      },
      {
        id: 'turmeric',
        title: 'Turmeric',
        image: '/products/spices/kanthari.png',
        description: 'Vibrant turmeric powder, known for its color and health benefits.',
        href: '#',
      },
      {
        id: 'dry_ginger',
        title: 'Dry Ginger',
        image: '/products/spices/dried-ginger.png',
        description: 'Dried ginger with a sharp, spicy aroma, used in cooking and medicine.',
        href: '#',
      },
      {
        id: 'chilli',
        title: 'Chilli',
        image: '/products/spices/turmeric.png',
        description: "Spicy bird's eye chilli (kanthari), packing a punch of heat.",
        href: '#',
      },
      {
        id: 'coriander',
        title: 'Coriander',
        image: '/products/spices/coriander.jpg',
        description: 'Aromatic coriander seeds/powder, adding citrusy notes to curries.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/spices',
  },
  {
    heading: 'Rice...',
    subheading: 'Premium quality rice and nutritious grains.',
    items: [
      {
        id: 'basmati_rice',
        title: 'Basmati Rice',
        image: '/products/rice/basmati.png',
        description:
          'Long-grain aromatic basmati rice, aged to perfection. Known for its distinctive fragrance and fluffy texture, ideal for biryanis, pulaos, and everyday meals.',
        href: '/products/basmati',
        featured: true,
      },
      {
        id: 'matta_rice',
        title: 'Matta Rice',
        image: '/products/rice/matta.png',
        description: 'Nutritious red parboiled rice, a staple of Kerala cuisine.',
        href: '#',
      },
      {
        id: 'mandhi_rice',
        title: 'Mandhi Rice',
        image: '/products/rice/mandhi.png',
        description: 'Special long-grain rice perfect for preparing authentic Mandhi dishes.',
        href: '#',
      },
      {
        id: 'jeeraka_rice',
        title: 'Jeeraka Rice',
        image: '/products/rice/jeeraka.png',
        description: 'Short-grain aromatic rice (Kaima rice), ideal for biryani and ghee rice.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/rice',
  },
  {
    heading: 'Snacks...',
    subheading: 'Traditional and delicious Kerala snacks.',
    items: [
      {
        id: 'banana_chips',
        title: 'Banana Chips',
        image: '/products/snacks/banana-chips.png',
        description:
          'Freshly roasted banana chips, perfect for snacking and adding a crunchy texture to your meals.',
        href: '/products/banana-chips',
        featured: true,
      },
      {
        id: 'spiced_mixture',
        title: 'Spiced Mixture',
        image: '/products/snacks/mixture.png',
        description: 'A spicy blend of crunchy savory items, perfect with tea.',
        href: '#',
      },
      {
        id: 'pakkavada',
        title: 'Pakkavada',
        image: '/products/snacks/pakkavada.png',
        description: 'Crispy ribbon pakoras made from rice flour and spices.',
        href: '#',
      },
      {
        id: 'tapioca_chips',
        title: 'Tapioca Chips',
        image: '/products/snacks/tapioca-chips.png',
        description: 'Thinly sliced tapioca fried to a crisp, a popular savory snack.',
        href: '#',
      },
      {
        id: 'jackfruit_chips',
        title: 'Jackfruit Chips',
        image: '/products/snacks/jackfruit-chips.png',
        description: 'Crunchy chips made from ripe or raw jackfruit, full of flavor.',
        href: '#',
      },
      {
        id: 'murukku',
        title: 'Murukku',
        image: '/products/snacks/murukku.png',
        description: 'Crunchy twisted savory snack made from rice and urad dal flour.',
        href: '#',
      },
      {
        id: 'sharkara_varatti',
        title: 'Sharkara Varatti',
        image: '/products/snacks/sharkara-varatti.png',
        description: 'Thick banana chips coated in sweet jaggery and spices.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/snacks',
  },
  {
    heading: 'Masala...',
    subheading: 'Authentic Indian masala and flavorful condiments.',
    items: [
      {
        id: 'jeerakam_powder',
        title: 'Jeerakam Powder',
        image: '/products/jeerakam-p.png',
        description:
          'Finely ground jeerakam (cumin) powder, known for its warm, earthy aroma and essential in many Indian dishes.',
        href: '/products/jeerakam-powder',
        featured: true,
      },
      {
        id: 'sambar_powder',
        title: 'Sambar Powder',
        image: '/products/sambar-p.png',
        description: 'Authentic spice blend for making the perfect vegetable Sambar.',
        href: '#',
      },
      {
        id: 'paprika_powder',
        title: 'Paprika Powder',
        image: '/products/paprika-p.png',
        description: 'Mild and colorful chilli powder made from sweet peppers.',
        href: '#',
      },
      {
        id: 'whole_turmeric',
        title: 'Whole Turmeric',
        image: '/products/whole-turmeric-p.png',
        description: 'Dried whole turmeric roots, ready to be ground or used in cooking.',
        href: '#',
      },
      {
        id: 'rasam_powder',
        title: 'Rasam Powder',
        image: '/products/rasam-p.png',
        description: 'Aromatic spice mix for preparing tangy and spicy Rasam soup.',
        href: '#',
      },
      {
        id: 'black_pepper_powder',
        title: 'Black Pepper Powder',
        image: '/products/black-pepper-p.png',
        description: 'Finely ground black pepper for seasoning and spicing up dishes.',
        href: '#',
      },
      {
        id: 'red_chilli_powder',
        title: 'Red Chilli Powder',
        image: '/products/red-chilli-p.png',
        description: 'Hot and spicy red chilli powder to add heat to your curries.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/masala',
  },
  {
    heading: 'Pickles...',
    subheading: 'Tangy, spicy, and authentic Kerala pickles to tantalize your taste buds.',
    items: [
      {
        id: 'garlic_pickles',
        title: 'Garlic Pickles',
        image: '/products/garlic-pickles-p.png',
        description: 'A spicy and tangy pickle made from fresh garlic cloves, perfect with any meal.',
        href: '/products/garlic-pickles',
        featured: true,
      },
      {
        id: 'cut_mango_pickles',
        title: 'Cut Mango Pickles',
        image: '/products/cut-mango-pickles-p.png',
        description: 'Traditional raw mango pickle, spicy and full of flavor.',
        href: '#',
      },
      {
        id: 'lime_pickles',
        title: 'Lime Pickles',
        image: '/products/lime-pickles-p.png',
        description: 'Zesty lime pickle, a perfect accompaniment to rice and curries.',
        href: '#',
      },
      {
        id: 'ginger_pickles',
        title: 'Ginger Pickles',
        image: '/products/ginger-pickles-p.png',
        description: 'Sweet, sour, and spicy ginger pickle (Inji Curry style).',
        href: '#',
      },
      {
        id: 'dates_pickles',
        title: 'Dates Pickles',
        image: '/products/dates-pickles-p.png',
        description: 'Sweet and tangy pickle made from premium dates.',
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/pickles',
  },
  {
    heading: 'Zere Specials...',
    subheading: 'Discover our exclusive range of specialty powders, snacks, and unique culinary delights.',
    items: [
      {
        id: 'appam_podi',
        title: 'Appam Podi',
        image: '/products/appam-podi-p.png',
        description: 'A spicy and tangy pickle made from fresh garlic cloves, perfect with any meal.',
        href: '/products/appam-podi',
        featured: true,
      },
      {
        id: 'steamed_puttu_podi',
        title: 'Steamed Puttu Podi',
        image: '/products/steamed-puttu-podi-p.png',
        description: 'Special rice flour blend for making extra soft steamed puttu.',
        href: '#',
      },
      {
        id: 'roasted_rava',
        title: 'Roasted Rava',
        image: '/products/roasted-rava-p.png',
        description: 'Double roasted semolina for non-sticky upma and sweets.',
        href: '#',
      },
      {
        id: 'matta_aval',
        title: 'Matta Aval',
        image: '/products/matta-aval-p.png',
        description: 'Nutritious flattened rice from Matta rice grains.',
        href: '#',
      },
      {
        id: 'roasted_matta_aval',
        title: 'Roasted Matta Aval',
        image: '/products/roasted-matta-aval-p.png',
        description: 'Crispy roasted flattened rice, ready to eat or use in mixes.',
        href: '#',
      },
      {
        id: 'avlose_podi',
        title: 'Avlose Podi',
        image: '/products/avlose-podi-p.png',
        description: 'Traditional roasted rice flour snack with coconut and cumin.',
        href: '#',
      },
      {
        id: 'kanthari_mango_chutney',
        title: 'Kanthari Mango Chutney',
        image: '/products/kanthari-mango-chutney-p.png',
        description: "Spicy chutney made with bird's eye chilli and raw mango.",
        href: '#',
      },
      {
        id: 'kanthari_gooseberry_chutney',
        title: 'Kanthari Gooseberry Chutney',
        image: '/products/kanthari-gooseberry-chutney-p.png',
        description: "Tangy and spicy chutney with gooseberry and bird's eye chilli.",
        href: '#',
      },
    ],
    ctaText: 'View All',
    ctaHref: '/products/category/zere-specials',
  },
];
