export const productsData = {
  coconut: {
    hero: {
      backgroundImage: '/image/coconutbg.jpg',
      title: 'Coconut Products',
      subtitle: 'Freshly processed, hygienically packed, and ready for international markets.',
    },
    productDetails: {
      title: 'Product Description',
      description:
        'Coconut Products from Zenith Reach are prepared from hand-picked, farm-fresh coconuts sourced from Kerala - the land of coconuts. With modern processing methods, we ensure natural taste, aroma, and nutrition stay intact. Ideal for curries, desserts, bakery items, and traditional Indian cooking, bringing authentic flavor to kitchens worldwide.',
      variants: [
        {
          id: 'grated-coconut',
          name: 'Grated Coconut',
          description: 'Freshly grated and frozen to lock in natural flavor.',
          uses: 'Ideal for chutneys, curries, sweets, and baking.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/products/coconut-p2.jpeg',
        },
        {
          id: 'sliced-coconut',
          name: 'Sliced Coconut',
          description: 'Thinly sliced coconut pieces, frozen to preserve texture and taste.',
          uses: 'Perfect for snacks, frying, and traditional recipes.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/products/coconut-p2.jpeg',
        },
      ],
      exportDetails: {
        form: 'Frozen',
        shelfLife: '12 months (under frozen conditions)',
        packaging: 'Hygienic, vacuum-sealed / LDPE food-grade pouches',
        qualityStandards: 'Processed as per international food safety & export norms',
      },
      mainImage: '/image/coconutbg.jpg',
      thumbnailImages: ['/products/coconut/coconut-p1.jpeg', '/products/coconut/coconut-p2.jpeg'],
    },
    whyChooseUs: {
      title: 'Why Choose Our Coconut Products?',
      benefits: [
        { id: 'b1', text: 'Farm-fresh coconuts from Kerala' },
        { id: 'b2', text: 'Hygienically processed & frozen to lock freshness' },
        { id: 'b3', text: 'Preserves authentic aroma, texture, and nutrition' },
        { id: 'b4', text: 'Suitable for global cuisines and food industries' },
      ],
      image: '/products/coconut/coconut-p3.png',
      imageAlt: 'Fresh coconuts',
      rightTitle: 'Bring the authentic taste of Kerala coconuts to your customers.',
    },
  },
  'cut-vegetables': {
    hero: {
      backgroundImage: '/banners/vegetable-bg.jpeg',
      title: 'Cut Vegetables',
      subtitle: 'Freshly cut, hygienically packed, and ready for global kitchens.',
    },
    productDetails: {
      title: 'Product Description',
      description:
        'Zenith Reach offers a wide range of freshly cut and cleaned vegetables, sourced directly from trusted farms. Each vegetable is hand-picked, washed, and hygienically packed to retain natural taste, texture, and nutrition. Convenient and ready-to-cook, our vegetable range brings authentic flavor and farm-fresh goodness to every kitchen worldwide.',
      variants: [
        {
          id: 'bitter-gourd',
          name: 'Bitter Gourd',
          description: 'Freshly cut pieces, perfect for fries, curries, and stir-fry recipes.',
          //   uses: 'Ideal for traditional Indian cooking and healthy dishes.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/bittergourd.jpg',
        },
        /*?
        {
            id: 'breadfruit',
            name: 'Breadfruit',
            description: 'Tender slices, ideal for curries and Kerala-style recipes.',
            uses: 'Perfect for authentic coastal dishes.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/breadfruit.jpg',
        },
        */
        {
          id: 'drumstick',
          name: 'Drumstick',
          description: 'Cleaned and cut drumstick pieces. Ready for sambar, avial, and curries.',
          //   uses: 'Ready for sambar, avial, and curries.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/drumstick.jpg',
        },
        /*
        {
            id: 'ash-gourd',
            name: 'Ash Gourd',
            description: 'Peeled and cut, fresh and nutrient-rich.',
          uses: 'Perfect for kootu, avial, soups, and desserts.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/ashgourd.jpg',
        },
        {
          id: 'green-chilly',
          name: 'Green Chilly',
          description: 'Washed and cut fresh chillies.',
          uses: 'Perfect for seasoning, pickles, and curries.',
          packSizes: ['100g', '200g'],
          image: '/image/vegetables/greenchilly.jpg',
        },
        {
          id: 'ivy-gourd',
          name: 'Ivy Gourd',
          description: 'Fresh-cut pieces of tender ivy gourd.',
          uses: 'Ideal for stir-fries and thoran.',
          //   packSizes: ['200g', '500g'],
          image: '/image/vegetables/ivygourd.jpg',
        },
        {
          id: 'ladies-finger',
          name: 'Ladies Finger (Okra)',
          description: 'Tender-cut okra pieces.',
          uses: 'Perfect for bhindi fry, curries, and sambar.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/okra.jpg',
        },
        {
            id: 'long-beans',
          name: 'Long Beans',
          description: 'Trimmed and cut long beans.',
          uses: 'Ideal for avial, stir-fries, and salads.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/longbeans.jpg',
        },
        {
            id: 'potato',
          name: 'Potato',
          description: 'Peeled and diced potatoes.',
          uses: 'Convenient for fries, curries, and gravies.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/potato.jpg',
        },
        {
            id: 'french-beans',
            name: 'French Beans',
            description: 'Cleaned and cut beans.',
            uses: 'Perfect for stir-fries and mixed dishes.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/frenchbeans.jpg',
        },
        {
            id: 'green-peas',
          name: 'Green Peas',
          description: 'Fresh shelled peas.',
          uses: 'Ideal for pulao, curries, and snacks.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/greenpeas.jpg',
        },
        {
            id: 'snake-gourd',
          name: 'Snake Gourd',
          description: 'Cut rings of fresh snake gourd.',
          uses: 'Perfect for stir-fries and Kerala-style curries.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/snakegourd.jpg',
        },
        {
          id: 'red-spinach',
          name: 'Red Spinach',
          description: 'Cleaned and chopped red spinach leaves.',
          uses: 'Ready for stir-fries and curries.',
          //   packSizes: ['200g', '500g'],
          image: '/image/vegetables/redspinach.jpg',
        },
        {
            id: 'sambar-mix',
            name: 'Sambar Mix',
          description: 'A ready mix of sambar vegetables.',
          uses: 'Perfect for authentic South Indian sambar.',
          packSizes: ['500g', '1kg'],
          image: '/image/vegetables/sambarmix.jpg',
        },
        {
          id: 'shallots',
          name: 'Shallots / Red Onion',
          description: 'Peeled and cut shallots & onions.',
          uses: 'Ideal for gravies, curries, and seasoning.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/shallots.jpg',
        },
        {
            id: 'baby-jackfruit',
          name: 'Baby Jackfruit Pieces',
          description: 'Cleaned and cut baby jackfruit.',
          uses: 'Perfect for curries and stir-fries.',
          packSizes: ['500g', '1kg'],
          image: '/image/vegetables/babyjackfruit.jpg',
        },
        {
            id: 'chinese-potato',
          name: 'Chinese Potato',
          description: 'Peeled and sliced Chinese potatoes.',
          uses: 'Great for traditional Kerala dishes.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/chinesepotato.jpg',
        },
        {
          id: 'gooseberry',
          name: 'Gooseberry',
          description: 'Cleaned and cut fresh gooseberries.',
          uses: 'Suitable for pickles, chutneys, and juices.',
          //   packSizes: ['200g', '500g'],
          image: '/image/vegetables/gooseberry.jpg',
        },
        {
            id: 'yam',
          name: 'Yam',
          description: 'Peeled and diced yam pieces.',
          uses: 'Ideal for curries, fries, and stir-fries.',
          packSizes: ['500g', '1kg'],
          image: '/image/vegetables/yam.jpg',
        },
        */
        {
          id: 'raw-mango',
          name: 'Raw Mango',
          description: 'Cut slices of raw mango.',
          //   uses: 'Perfect for pickles, curries, and chutneys.',
          packSizes: ['200g', '500g', '1kg'],
          image: '/image/vegetables/rawmango.jpg',
        },
      ],
      exportDetails: {
        form: 'Fresh-cut & Frozen',
        shelfLife: '12 months (under frozen conditions)',
        packaging: 'Hygienic, vacuum-sealed / LDPE food-grade pouches',
        qualityStandards: 'Processed as per international food safety & export norms',
      },
      mainImage: '/image/vegetablesbg.jpg',
      thumbnailImages: ['/products/vegetables/vegetable-p1.jpeg', '/products/vegetables/vegetable-p2.jpeg'],
    },
    whyChooseUs: {
      title: 'Why Choose Our Cut Vegetables?',
      benefits: [
        { id: 'v1', text: 'Sourced from trusted farms' },
        { id: 'v2', text: 'Hygienically cleaned & frozen to lock freshness' },
        { id: 'v3', text: 'Preserves natural taste, texture, and nutrition' },
        { id: 'v4', text: 'Ready-to-cook convenience for busy kitchens' },
        { id: 'v5', text: 'Suitable for global cuisines & food industries' },
      ],
      image: '/products/vegetables/vegetable-p3.jpeg',
      imageAlt: 'Fresh cut vegetables',
      rightTitle: 'Farm-fresh cut vegetables, bringing convenience and authentic taste.',
    },
  },
  'ready-to-eat-snacks': {
    hero: {
      backgroundImage: '/banners/snacks-b.jpeg',
      title: 'Ready-to-Eat Snacks',
      subtitle: 'Snack it till you make it! Traditional taste, modern convenience.',
    },
    productDetails: {
      title: 'Product Description',
      description:
        'Zenith Reach brings you an authentic range of Ready-to-Eat snacks, crafted with farm-fresh ingredients and traditional recipes. Hygienically prepared and frozen to preserve authentic flavor, texture, and nutrition, these snacks are convenient, tasty, and perfect for any occasion. From tea-time favorites to festive delights, enjoy Kerala’s traditional flavors with global quality standards.',
      variants: [
        /*
        {
            id: 'kumbilappam',
          name: 'Kumbilappam',
          description:
            'Traditional steamed snack made with jackfruit, rice flour, and jaggery, wrapped in bay leaves.',
          uses: 'Perfect for tea-time or festive occasions.',
          //   packSizes: ['200g', '500g'],
          image: '/products/snacks/kumbilappam.jpg',
        },
        {
          id: 'aloo-bonda',
          name: 'Aloo Bonda',
          description: 'Golden-fried snack with spicy mashed potato filling.',
          uses: 'Ideal for tea-time or as a party snack.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/aloobonda.jpg',
        },
        {
          id: 'elayada-jaggery',
          name: 'Elayada (Jaggery)',
          description: 'Steamed rice parcels filled with coconut and jaggery, wrapped in banana leaves.',
          uses: 'Perfect for festivals and sweet cravings.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/elayadajaggery.jpg',
        },
        {
          id: 'veg-spring-roll',
          name: 'Veg Spring Roll',
          description: 'Crispy rolls filled with seasoned vegetables.',
          uses: 'Great for starters, parties, and kids’ snacks.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/vegspringroll.jpg',
        },
        {
          id: 'elayada-jackfruit',
          name: 'Elayada (Jackfruit)',
          description: 'Steamed rice flour wraps with jackfruit filling, a traditional Kerala delicacy.',
          uses: 'Ideal for festivals and celebrations.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/elayadajackfruit.jpg',
        },
        {
          id: 'kozhukkatta',
          name: 'Kozhukkatta',
          description: 'Steamed rice dumplings filled with sweet coconut and jaggery.',
          uses: 'A classic breakfast and evening snack.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/kozhukkatta.jpg',
        },
        {
          id: 'aloo-tikki',
          name: 'Aloo Tikki',
          description: 'Crispy potato patties with mild spices.',
          uses: 'Perfect for chaats, burgers, or evening snacks.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/alootikki.jpg',
        },
        {
            id: 'banana-roast',
            name: 'Banana Roast',
            description: 'Ripe banana fritters coated in batter and fried.',
            uses: 'A tea-time favorite in Kerala households.',
            //   packSizes: ['200g', '500g'],
            image: '/image/snacks/bananaroast.jpg',
        },
        {
            id: 'punjabi-samosa',
            name: 'Punjabi Samosa',
            description: 'Crispy pastry pockets filled with spiced potatoes and peas.',
            uses: 'Best served with chutney or tea.',
            //   packSizes: ['200g', '500g'],
            image: '/image/snacks/punjabisamosa.jpg',
        },
        */
        {
          id: 'uzhunnu-vada',
          name: 'Uzhunnu Vada',
          description: 'Crispy and fluffy lentil doughnuts, a South Indian classic.',
          //   uses: 'Perfect with coconut chutney and sambar.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/uzhunnuvada.jpg',
        },
        /*
        {
            id: 'veg-nuggets',
            name: 'Vegetable Nuggets',
            description: 'Crispy nuggets made with fresh vegetables.',
            uses: 'Great for kids and quick snacks.',
            //   packSizes: ['200g', '500g'],
            image: '/image/snacks/vegnuggets.jpg',
        },
        */
        {
          id: 'parippu-vada',
          name: 'Parippu Vada',
          description: 'Crispy lentil fritters, crunchy and flavorful.',
          //   uses: 'A popular tea-time snack in South India.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/parippuvada.jpg',
        },
        /*
        {
            id: 'veg-samosa',
            name: 'Vegetable Samosa',
          description: 'Golden-fried samosas with spiced vegetable filling.',
          uses: 'Perfect for snacks, parties, and festivals.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/vegsamosa.jpg',
        },
        {
            id: 'unniyappam',
          name: 'Unniyappam',
          description: 'Sweet rice fritters made with jaggery and banana.',
          uses: 'A traditional Kerala sweet snack.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/unniyappam.jpg',
        },
        {
          id: 'banana-fry',
          name: 'Banana Fry',
          description: 'Golden-fried raw banana slices.',
          uses: 'Ideal as a crispy side or evening snack.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/bananafry.jpg',
        },
        {
            id: 'neyyappam',
            name: 'Neyyappam',
            description: 'Traditional Kerala sweet snack made with rice, jaggery, and ghee.',
            uses: 'Perfect for festive occasions.',
            //   packSizes: ['200g', '500g'],
            image: '/image/snacks/neyyappam.jpg',
        },
        {
            id: 'unnakka',
          name: 'Unnakka',
          description: 'Sweet stuffed snack made with rice flour and coconut filling.',
          uses: 'A nostalgic Kerala evening snack.',
          //   packSizes: ['200g', '500g'],
          image: '/image/snacks/unnakka.jpg',
        },
        */
      ],
      exportDetails: {
        form: 'Ready-to-eat, Frozen',
        shelfLife: '1 months (under frozen conditions)',
        packaging: 'Hygienic, vacuum-sealed / LDPE food-grade pouches',
        qualityStandards: 'Processed as per international food safety & export norms',
      },
      mainImage: '/image/snacksbg.jpg',
      thumbnailImages: ['/products/snacks/snacks-p2.jpeg', '/products/snacks/snacks-p1.jpg'],
    },
    whyChooseUs: {
      title: 'Why Choose Our Ready-to-Eat Snacks?',
      benefits: [
        { id: 's1', text: 'Authentic Kerala & Indian recipes' },
        { id: 's2', text: 'Farm-fresh ingredients, hygienically processed' },
        { id: 's3', text: 'Frozen to retain authentic taste and freshness' },
        { id: 's4', text: 'Wide range of traditional & modern snacks' },
        { id: 's5', text: 'Convenient, ready in minutes' },
      ],
      image: '/products/snacks/snacks-p3.jpeg',
      imageAlt: 'Ready to eat snacks',
      rightTitle: 'Bring the authentic taste of Kerala snacks to your customers.',
    },
  },
  porrota: {
    hero: {
      backgroundImage: '/banners/porotta-b.png',
      title: 'Porotta Variants',
      subtitle: 'The magical Indian bread! Soft, flaky, and packed with flavor.',
    },
    productDetails: {
      title: 'Product Description',
      description:
        'Zenith Reach presents a wide variety of authentic Indian breads, crafted with premium ingredients and traditional recipes. From the flaky Malabar Porotta to stuffed Parathas, our frozen porotta range offers the perfect balance of taste, texture, and convenience. Hygienically prepared and frozen to lock in freshness, these breads are ideal for homes, restaurants, and global food markets.',
      variants: [
        {
          id: 'malabar-porotta',
          name: 'Malabar Porotta',
          description: 'Flaky and layered flatbread, a signature Kerala delight.',
          uses: 'Perfect with curries, gravies, or as a standalone snack.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/malabar.jpg',
        },
        {
          id: 'methi-paratha',
          name: 'Methi Paratha',
          description: 'Whole wheat paratha flavored with fresh fenugreek leaves.',
          uses: 'Ideal for breakfast or as a healthy meal option.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/methi.jpg',
        },
        {
          id: 'coin-porotta',
          name: 'Coin Porotta',
          description: 'Mini-sized flaky porottas, soft and layered.',
          uses: 'Perfect for kids, tiffins, and party servings.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/coin.jpg',
        },
        {
          id: 'kerala-porotta',
          name: 'Kerala Porotta',
          description: 'Authentic hand-tossed porotta with fluffy layers.',
          uses: 'A Kerala staple, best paired with spicy curries.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/kerala.jpg',
        },
        {
          id: 'paneer-paratha',
          name: 'Paneer Paratha',
          description: 'Whole wheat paratha stuffed with seasoned cottage cheese.',
          uses: 'Great for breakfast, lunch boxes, or a quick snack.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/paneer.jpg',
        },
        {
          id: 'kothu-parotta',
          name: 'Kothu Parotta',
          description: 'Chopped porotta stir-fried with spices and curry.',
          uses: 'A popular street-food style dish, ready-to-heat and serve.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/kothu.jpg',
        },
        {
          id: 'ceylon-parotta',
          name: 'Ceylon Parotta',
          description: 'Soft, layered parotta with a light and delicate texture.',
          uses: 'Pairs perfectly with gravies and non-veg curries.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/ceylon.jpg',
        },
        {
          id: 'palak-paratha',
          name: 'Palak Paratha',
          description: 'Whole wheat paratha blended with fresh spinach.',
          uses: 'Nutritious and tasty, great for kids and health-conscious meals.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/palak.jpg',
        },
        {
          id: 'aloo-paratha',
          name: 'Aloo Paratha',
          description: 'Classic North Indian stuffed paratha with spiced potatoes.',
          uses: 'Perfect with butter, curd, or pickle.',
          packSizes: ['400g', '800g', '1kg'],
          image: '/image/porotta/aloo.jpg',
        },
      ],
      exportDetails: {
        form: 'Ready-to-cook, Frozen',
        shelfLife: '12 months (under frozen conditions)',
        packaging: 'Hygienic, vacuum-sealed / LDPE food-grade pouches',
        qualityStandards: 'Processed as per international food safety & export norms',
      },
      mainImage: '/image/porottabg.jpg',
      thumbnailImages: ['/products/porotta/porotta-p1.jpg', '/products/porotta/porotta-p2.jpg'],
    },
    whyChooseUs: {
      title: 'Why Choose Our Porotta Variants?',
      benefits: [
        { id: 'p1', text: 'Authentic recipes with soft, flaky layers' },
        { id: 'p2', text: 'Wide variety from plain porottas to stuffed parathas' },
        { id: 'p3', text: 'Frozen to lock in freshness and texture' },
        { id: 'p4', text: 'Quick and convenient, ready in minutes' },
        { id: 'p5', text: 'Perfect for homes, restaurants, and exports' },
      ],
      image: '/products/porotta/porotta-p3.jpg',
      imageAlt: 'Variety of porottas and parathas',
      rightTitle: 'From Kerala kitchens to global tables – the magic of Indian bread.',
    },
  },
};
